// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO54bYYw5jaVjanUlp6OZ2v_r_jCv5QXQ',
    appId: '1:797256838210:web:131976b3b57b73572a51db',
    messagingSenderId: '797256838210',
    projectId: 'babyshop-cb751',
    authDomain: 'babyshop-cb751.firebaseapp.com',
    storageBucket: 'babyshop-cb751.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO6f2CKiYHN6HLniAnNkIwmNqRBbKHTK0',
    appId: '1:797256838210:android:001617ebedd352212a51db',
    messagingSenderId: '797256838210',
    projectId: 'babyshop-cb751',
    storageBucket: 'babyshop-cb751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATrTcmXBs05Ad1qubV8ddUqDhJNV54UpU',
    appId: '1:797256838210:ios:b6794aa2da85c1732a51db',
    messagingSenderId: '797256838210',
    projectId: 'babyshop-cb751',
    storageBucket: 'babyshop-cb751.firebasestorage.app',
    iosBundleId: 'com.example.babyshopHub',
  );
}
